In [16]:
import pandas as pd
import numpy as np

In [17]:
# 스펠링 검사가 끝난 데이터를 이용할 것입니다.
# 스펠링 검사 코드는 다른 파일을 참고해주세요.

df = pd.read_csv('[31]top_10_spell.csv')
df['spell'] = df['spell'].astype(str)
df.head()

,info,date,rating,title,name,spell
0,마케팅·홍보 전문가,2023.11.07,2.0,내가 발전할 수 없는 회사,cjENM,내가 발전할 수 없는 회사
1,상품기획·MD·디자이너,2023.11.15,5.0,괜찮은 회사,cjENM,괜찮은 회사
2,마케팅·홍보 전문가,2023.11.10,3.0,오래 있기 어려운 곳,cjENM,오래 있기 어려운 곳
3,IT 엔지니어,2023.11.06,2.0,위태로운 회사,cjENM,위태로운 회사
4,상품기획·MD·디자이너,2023.11.03,2.0,적당한 급여 그리고 적당히 다니기 괜찮은 곳,cjENM,적당한 급여 그리고 적당히 다니기 괜찮은 곳

In [18]:
print(df.name.unique())
print(df.info())

print('TOP 10 리뷰 평균 평점: {:.3f}'.format(np.mean(df.rating)))

['cjENM' 'cj제일제당' 'sk하이닉스' '네이버' '대한항공' '삼성물산' '삼성전자' '아모레퍼시픽' '카카오'
 '현대자동차']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34397 entries, 0 to 34396
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   info    34397 non-null  object
 1   date    34397 non-null  object
 2   rating  34397 non-null  float64
 3   title   34384 non-null  object
 4   name    34397 non-null  object
 5   spell   34397 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.6+ MB
None
TOP 10 리뷰 평균 평점: 3.218

In [19]:
df[df['name']=='네이버'] # 네이버 회사의 리뷰

,info,date,rating,title,name,spell
8103,IT 디자이너,2023.09.25,2.0,생각보다 여러모로 퇴보적이고 경직된 회사,네이버,생각보다 여러모로 퇴보적이고 경직된 회사
8104,IT 기획·매니지먼트 전문가,2023.11.14,5.0,시쳇말로 육각형 회사,네이버,시쳇말로 육각형 회사
8105,IT 엔지니어,2023.11.13,5.0,좋은 회사,네이버,좋은 회사
8106,정보보안·IT보안,2023.11.09,4.0,워라밸 보장되고 복지 급여 상위 티어급 회사,네이버,워라밸 보장되고 복지 급여 상위 티어급 회사
8107,경영지원·관리 전문가,2023.11.09,4.0,워라밸은 부마부,네이버,워라밸은 부마부
...,...,...,...,...,...,...
11276,IT 엔지니어,2020.07.31,5.0,네임밸류 최강임,네이버,네임밸류 최강임
11277,마케팅·홍보 전문가,2020.07.31,4.0,전반적으로 만족스러운 직장 성장의 정점에 다다랐나 싶어서 다소 불안함,네이버,전반적으로 만족스러운 직장 성장의 정점에 다다랐나 싶어서 다소 불안함
11278,IT 엔지니어,2020.07.31,5.0,성장하려는 의지만 있다면 무한히 성장할 수 있는 회사,네이버,성장하려는 의지만 있다면 무한히 성장할 수 있는 회사
11279,경영전략·사업기획·분석전문가,2020.07.31,5.0,수평적인 분위기로 자유로워 보이지만 평가를 받아야 한다는 압박감,네이버,수평적인 분위기로 자유로워 보이지만 평가를 받아야 한다는 압박감
11280,IT 엔지니어,2020.07.31,5.0,개발자로서 좋은 대우를 받으며 꾸준히 성장할 수 있는 곳,네이버,개발자로서 좋은 대우를 받으며 꾸준히 성장할 수 있는 곳

In [20]:
# 맞춤법 검사가 끝난 문장 추가 전처리

df['spell'] = df['spell'].apply(lambda x:x.replace('오라 밸', '워라밸'))
df['spell'] = df['spell'].apply(lambda x:x.replace('워라밸만', '워라밸'))
df['spell'] = df['spell'].apply(lambda x:x.replace('워라밸이', '워라밸'))
df['spell'] = df['spell'].apply(lambda x:x.replace('워라밸은', '워라밸'))

df['spell'] = df['spell'].apply(lambda x:x.replace('커리어', '커리어'))
df['spell'] = df['spell'].apply(lambda x:x.replace('커리', '커리어'))
df['spell'] = df['spell'].apply(lambda x:x.replace('커리 어', '커리어'))
df['spell'] = df['spell'].apply(lambda x:x.replace('직업', '커리어'))

df['spell'] = df['spell'].apply(lambda x: x.replace('비젼', '비전'))
df['spell'] = df['spell'].apply(lambda x: x.replace('그냥저냥', '그저 그런'))
df['spell'] = df['spell'].apply(lambda x: x.replace('걍', '그냥'))
df['spell'] = df['spell'].apply(lambda x: x.replace('캐이비', 'KB'))
df['spell'] = df['spell'].apply(lambda x: x.replace('It', 'IT'))

df['spell'] = df['spell'].apply(lambda x: x.replace('부바부', '부서 간 차이 있음'))
df['spell'] = df['spell'].apply(lambda x: x.replace('부마부', '부서 간 차이 있음'))

df['spell'] = df['spell'].apply(lambda x: x.replace('개바개', '개인 간 차이 있음'))
df['spell'] = df['spell'].apply(lambda x: x.replace('팀바팀', '팀별 차이 있음'))
df['spell'] = df['spell'].apply(lambda x: x.replace('케바케', '상황마다 다름'))
df['spell'] = df['spell'].apply(lambda x: x.replace('캐바캐', '상황마다 다름'))
df['spell'] = df['spell'].apply(lambda x: x.replace('사바사', '사람마다 다름'))

df['spell'] = df['spell'].apply(lambda x: x.replace('빵빵', '넉넉함'))
df['spell'] = df['spell'].apply(lambda x: x.replace('so so', '보통'))
df['spell'] = df['spell'].apply(lambda x: x.replace('soso', '보통'))
df['spell'] = df['spell'].apply(lambda x: x.replace('쏘쏘', '보통'))
df['spell'] = df['spell'].apply(lambda x: x.replace('쏘소', '보통'))
df['spell'] = df['spell'].apply(lambda x: x.replace('소쏘', '보통'))

df['spell'] = df['spell'].apply(lambda x: x.replace('고인 물', '고인물'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워러벨', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워라벨', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워라맬', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워라멜', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워리벨', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('워리밸', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('와 라벨', '워라밸'))
df['spell'] = df['spell'].apply(lambda x: x.replace('와 라밸', '워라밸'))

In [21]:
!apt-get update
!apt-get install g++ openjdk-8-jdk python-dev python3-dev # 오류 해결 명령어

!pip3 install JPype1-py3 # 파이썬 언어와 자바 언어의 중간 다리 JPype1-py3
!pip3 install konlpy

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 229 kB in 2s (145 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev python2 python-dev-is-python3

E: Package 'python-dev' has no installation candidate
Requirement already satisfied: JPype1-py3 in /usr/local/lib/python3.10/dist-packages (0.5.5.4)
Requirement already satisfied: konlpy in /usr/local/lib/python3.10/dist-packages (0.6.0)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.4.1)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.3)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (23.2)

In [22]:
# 한국어 형태소 분석

from konlpy.tag import Kkma, Komoran, Hannanum, Okt
kkma = Kkma()
komoran = Komoran()
hannanum = Hannanum()
okt = Okt()

In [34]:
def keyword(data, mode, name=None): # 빈도 수를 확인해서 리뷰가 많이 등장하는 키워드 찾기
  from collections import Counter
  from konlpy.tag import Kkma, Komoran, Hannanum, Okt
  if name == None:
    data = data
  else:
    data = data[data['name']==name]
  words = ' '.join(list(data['spell']))

  # morphs_lst = komoran.morphs(words)
  pos_lst = mode.pos(words)

  # 불용어 제거
  with open('./[30]stopword_ko.txt') as f:
    stop_words = f.read().splitlines()
    f.close()

  stop_words.append('수')
  stop_words.append('곳')
  stop_words.append('것')
  stop_words.append('만')

  cleaned_words = [word for word in pos_lst if word[0] not in stop_words]

  nouns = [word for word in cleaned_words
           if word[1].startswith('N') | word[1].startswith('V')]

  count_nouns = Counter(nouns)
  count_nouns_list = count_nouns.most_common(20)

  return count_nouns_list

# 2.  TF-IDF를 이용한 회사별 & 전체 키워드
# *   회사별 키워드 분석
# *   전체 리뷰 키워드 분석

def vectorize(data, name=None): # 각 리뷰 내 키워드가 전체 문서에도 중요한 키워드인지 파악하기
  from sklearn.feature_extraction.text import TfidfVectorizer

  if name == None:
    data = data
  else:
    data = data[data['name']==name]

  data = data[data['name']== name]['spell']
  tfidf_vectorizer = TfidfVectorizer(max_features= 1000)
  tfidf_vectorizer.fit(data)
  vocab = tfidf_vectorizer.vocabulary_
  text_tfidf = tfidf_vectorizer.transform(data).toarray()

  # 가중치 0.6 이상의 단어
  weight = 0.6
  vocab_c = {v:k for k,v in vocab.items()}
  words_lst = []
  for item in text_tfidf:
    words = []
    for index, value in enumerate(item):
      if value >= weight:
        words.append(vocab_c[index])
    words_lst.append(words)

  # best_keyword
  tfidf_top = [vocab_c[text.argmax()] for text in text_tfidf]

  return pd.DataFrame(data=zip(df[df['name']==name]['spell'], words_lst, tfidf_top),
                      columns = ['리뷰', 'Above_T', 'top_keyword'])

def collocation(df, name): # 리뷰의 중요 키워드에 대해 어떤 단어가 같이 붙는지에 따라 리뷰의 형태가 달라지기에 "연어"를 확인하기
  import nltk
  from konlpy.tag import Kkma, Komoran, Hannanum, Okt
  from nltk.collocations import BigramAssocMeasures, TrigramAssocMeasures, QuadgramAssocMeasures
  from nltk.collocations import BigramCollocationFinder, TrigramCollocationFinder, QuadgramCollocationFinder

  bigram_measures = BigramAssocMeasures()
  trigram_measures = TrigramAssocMeasures()
  fourgram_measures = QuadgramAssocMeasures()

  # list의 data -> 한 문장으로
  data = df[df['name']==name]['spell']
  data = ' '.join(data)

  hannanum = Hannanum()

  word_lst = hannanum.morphs(data)

  with open('./[30]stopword_ko.txt') as f:
    stop_words = f.read().splitlines()
    f.close()

  cleaned_words = [word for word in word_lst if word[0] not in stop_words]

  bi_ngrams = BigramCollocationFinder.from_words(cleaned_words)
  tri_ngrams = TrigramCollocationFinder.from_words(cleaned_words)
  quad_ngrams = QuadgramCollocationFinder.from_words(cleaned_words)

  bi_ngrams.apply_freq_filter(2) # 최소 2번 등장하는 n-gram 필터링
  tri_ngrams.apply_freq_filter(2) # 최소 2번 등장하는 n-gram 필터링
  quad_ngrams.apply_freq_filter(2) # 최소 2번 등장하는 n-gram 필터링

  bi_result = bi_ngrams.nbest(bigram_measures.pmi, 10)
  tri_result = tri_ngrams.nbest(trigram_measures.pmi, 10)
  quad_result = quad_ngrams.nbest(fourgram_measures.pmi, 10)

  result = pd.DataFrame({'Bi_gram': bi_result,
                       'Tri_gram': tri_result,
                       'Quad_gram': quad_result})

  return result

In [35]:
# 'cjENM' 'cj제일제당' 'sk하이닉스' '네이버' '대한항공' '삼성물산' '삼성전자' '아모레퍼시픽' '카카오' '현대자동차'
# Kkma, Komoran, Hannanum, Okt
names = ['cjENM', 'cj제일제당', 'sk하이닉스', '네이버', '대한항공', '삼성물산', '삼성전자', '아모레퍼시픽', '카카오', '현대자동차']

# Kkma
keywords_kkma = pd.DataFrame(np.empty((20, 10)), columns=names)
for name in keywords_kkma.columns:
  keywords_kkma[name] = keyword(df, Kkma(),name)

keywords_komoran = pd.DataFrame(np.empty((20, 10)), columns=names)
for name in keywords_komoran.columns:
  keywords_komoran[name] = keyword(df, Komoran(),name)

keywords_hannanum = pd.DataFrame(np.empty((20, 10)), columns=names)
for name in keywords_hannanum.columns:
  keywords_hannanum[name] = keyword(df, Hannanum(),name)

keywords_Okt = pd.DataFrame(np.empty((20, 10)), columns=names)
for name in keywords_Okt.columns:
  keywords_Okt[name] = keyword(df, Okt(),name)

In [36]:
keywords_kkma

,cjENM,cj제일제당,sk하이닉스,네이버,대한항공,삼성물산,삼성전자,아모레퍼시픽,카카오,현대자동차
0,"((회사, NNG), 646)","((회사, NNG), 879)","((회사, NNG), 2612)","((회사, NNG), 1705)","((회사, NNG), 569)","((회사, NNG), 585)","((회사, NNG), 5079)","((배, VV), 836)","((회사, NNG), 1104)","((회사, NNG), 3408)"
1,"((좋, VA), 365)","((좋, VA), 304)","((좋, VA), 699)","((좋, VA), 832)","((라, NNG), 212)","((좋, VA), 214)","((좋, VA), 1659)","((라, NNG), 835)","((라, NNG), 742)","((라, NNG), 1961)"
2,"((라, NNG), 254)","((라, NNG), 243)","((라, NNG), 574)","((라, NNG), 321)","((배, VV), 206)","((라, NNG), 196)","((라, NNG), 1154)","((회사, NNG), 794)","((배, VV), 732)","((배, VV), 1947)"
3,"((배, VV), 252)","((배, VV), 240)","((배, VV), 564)","((배, VV), 318)","((좋, VA), 204)","((배, VV), 194)","((배, VV), 1134)","((좋, VA), 572)","((좋, VA), 696)","((좋, VA), 994)"
4,"((복지, NNG), 148)","((복지, NNG), 172)","((복지, NNG), 295)","((있, VV), 307)","((다니, VV), 119)","((보장, NNG), 99)","((돈, NNG), 644)","((보장, NNG), 312)","((보장, NNG), 286)","((보장, NNG), 733)"
5,"((보장, NNG), 128)","((대기업, NNG), 111)","((직원, NNG), 275)","((성장, NNG), 284)","((보장, NNG), 119)","((다니, VV), 76)","((다니, VV), 565)","((다니, VV), 134)","((있, VV), 176)","((없, VA), 395)"
6,"((다니, VV), 109)","((보장, NNG), 100)","((돈, NNG), 261)","((많, VA), 209)","((없, VA), 72)","((삼성, NNG), 61)","((있, VV), 479)","((복지, NNG), 130)","((성장, NNG), 118)","((다니, VV), 347)"
7,"((있, VV), 106)","((있, VV), 96)","((보장, NNG), 251)","((없, VA), 144)","((있, VV), 67)","((없, VA), 58)","((대기업, NNG), 472)","((최고, NNG), 78)","((문화, NNG), 106)","((직원, NNG), 283)"
8,"((없, VA), 71)","((없, VA), 94)","((없, VA), 249)","((복지, NNG), 133)","((않, VXV), 45)","((않, VXV), 55)","((없, VA), 460)","((팀, NNG), 62)","((경영진, NNG), 105)","((있, VV), 259)"
9,"((커리어, NNG), 60)","((다니, VV), 92)","((다니, VV), 232)","((보장, NNG), 130)","((직원, NNG), 39)","((있, VV), 53)","((부서, NNG), 401)","((있, VV), 60)","((복지, NNG), 89)","((대기업, NNG), 247)"
10,"((대기업, NNG), 51)","((식품, NNG), 78)","((대기업, NNG), 197)","((커리어, NNG), 130)","((대기업, NNG), 36)","((대기업, NNG), 45)","((보장, NNG), 401)","((문화, NNG), 55)","((최고, NNG), 86)","((않, VXV), 215)"
11,"((문화, NNG), 50)","((성장, NNG), 76)","((급여, NNG), 176)","((팀, NNG), 130)","((돈, NNG), 36)","((건설, NNG), 45)","((주, VV), 382)","((없, VA), 49)","((다니, VV), 85)","((연봉, NNG), 211)"
12,"((많, VA), 49)","((않, VXV), 75)","((괜찮, VA), 173)","((다니, VV), 129)","((괜찮, VA), 33)","((복지, NNG), 41)","((복지, NNG), 362)","((성장, NNG), 45)","((보상, NNG), 67)","((급여, NNG), 186)"
13,"((사람, NNG), 48)","((문화, NNG), 70)","((않, VXV), 166)","((최고, NNG), 115)","((문화, NNG), 32)","((많, VA), 39)","((최고, NNG), 350)","((괜찮, VA), 43)","((없, VA), 66)","((문화, NNG), 184)"
14,"((않, VXV), 41)","((많, VA), 70)","((있, VV), 156)","((동료, NNG), 108)","((보수적, NNG), 31)","((미래, NNG), 39)","((있음, NNG), 335)","((있음, NNG), 36)","((많, VA), 61)","((최고, NNG), 156)"
15,"((성장, NNG), 41)","((괜찮, VA), 47)","((주, VV), 148)","((보상, NNG), 94)","((사람, NNG), 30)","((중, NNB), 34)","((않, VXV), 325)","((사람, NNG), 36)","((동료, NNG), 58)","((있음, NNG), 154)"
16,"((업계, NNG), 41)","((기업, NNG), 45)","((보, VV), 147)","((괜찮, VA), 92)","((항공, NNG), 28)","((괜찮, VA), 32)","((많, VA), 301)","((않, VXV), 35)","((자유, NNG), 57)","((미래, NNG), 148)"
17,"((괜찮, VA), 38)","((업계, NNG), 43)","((행복, NNG), 145)","((문화, NNG), 90)","((욕심, NNG), 28)","((건설사, NNG), 30)","((차이, NNG), 291)","((많, VA), 34)","((카카오, NNG), 56)","((돈, NNG), 143)"
18,"((있음, NNG), 37)","((되, VV), 42)","((있음, NNG), 144)","((않, VXV), 87)","((일하, VV), 26)","((나쁘, VA), 28)","((커리어, NNG), 291)","((기업, NNG), 32)","((팀, NNG), 56)","((괜찮, VA), 140)"
19,"((팀, NNG), 34)","((커리어, NNG), 42)","((부서, NNG), 136)","((되, VV), 85)","((라벨, NNG), 24)","((급여, NNG), 28)","((급여, NNG), 268)","((미래, NNG), 32)","((대기업, NNG), 50)","((생각, NNG), 139)"

In [37]:
keywords_komoran

,cjENM,cj제일제당,sk하이닉스,네이버,대한항공,삼성물산,삼성전자,아모레퍼시픽,카카오,현대자동차
0,"((회사, NNG), 648)","((회사, NNG), 869)","((회사, NNG), 2608)","((회사, NNG), 1711)","((회사, NNG), 570)","((회사, NNG), 559)","((회사, NNG), 5057)","((워라밸, NA), 824)","((회사, NNG), 1104)","((회사, NNG), 3406)"
1,"((좋, VA), 364)","((좋, VA), 308)","((좋, VA), 755)","((좋, VA), 836)","((좋, VA), 203)","((좋, VA), 220)","((좋, VA), 1700)","((회사, NNG), 794)","((워라밸, NA), 719)","((워라밸, NA), 1909)"
2,"((워라밸, NA), 250)","((워라밸, NA), 233)","((워라밸, NA), 556)","((있, VV), 410)","((워라밸, NA), 202)","((워라밸, NA), 192)","((워라밸, NA), 1109)","((좋, VA), 572)","((좋, VA), 704)","((좋, VA), 1036)"
3,"((있, VV), 161)","((있, VV), 157)","((있, VV), 339)","((워라밸, NA), 312)","((다니, VV), 120)","((보장, NNG), 99)","((있, VV), 892)","((보장, NNG), 311)","((보장, NNG), 287)","((보장, NNG), 733)"
4,"((보장, NNG), 128)","((복지, NNG), 114)","((돈, NNG), 289)","((성장, NNG), 285)","((보장, NNG), 120)","((있, VV), 77)","((돈, NNG), 693)","((다니, VV), 139)","((있, VV), 250)","((있, VV), 473)"
5,"((다니, VV), 113)","((대기업, NNP), 109)","((직원, NNG), 275)","((많, VA), 209)","((있, VV), 91)","((다니, VV), 76)","((주, VX), 625)","((있, VV), 105)","((성장, NNG), 116)","((없, VA), 411)"
6,"((복지, NNG), 103)","((보장, NNG), 101)","((주, VX), 268)","((없, VA), 151)","((없, VA), 79)","((없, VA), 60)","((다니, VV), 574)","((최고, NNG), 80)","((경영진, NNG), 106)","((다니, VV), 352)"
7,"((없, VA), 72)","((없, VA), 100)","((없, VA), 255)","((다니, VV), 133)","((않, VX), 50)","((않, VX), 59)","((없, VA), 488)","((복지, NNP), 74)","((문화, NNG), 106)","((직원, NNG), 283)"
8,"((커리, NNP), 60)","((다니, VV), 96)","((보장, NNG), 251)","((보장, NNG), 131)","((직원, NNG), 38)","((삼성, NNP), 56)","((대기업, NNP), 470)","((팀, NNG), 63)","((다니, VV), 89)","((대기업, NNP), 247)"
9,"((복지, NNP), 52)","((않, VX), 78)","((다니, VV), 236)","((커리, NNP), 130)","((돈, NNG), 37)","((대기업, NNP), 45)","((부서, NNP), 410)","((복지, NNG), 60)","((최고, NNG), 86)","((않, VX), 238)"
10,"((많, VA), 50)","((성장, NNG), 76)","((대기업, NNP), 195)","((팀, NNG), 120)","((대기업, NNP), 36)","((미래, NNG), 39)","((보장, NNG), 399)","((문화, NNG), 56)","((없, VA), 68)","((연봉, NNG), 214)"
11,"((대기업, NNP), 50)","((문화, NNG), 70)","((개, NNB), 191)","((최고, NNG), 113)","((보수, NNG), 35)","((많, VA), 38)","((않, VX), 359)","((없, VA), 52)","((보상, NNG), 68)","((급여, NNG), 187)"
12,"((문화, NNG), 48)","((많, VA), 70)","((급여, NNG), 182)","((동료, NNG), 108)","((괜찮, VA), 33)","((나쁘, VA), 37)","((최고, NNG), 358)","((성장, NNG), 44)","((많, VA), 61)","((문화, NNG), 180)"
13,"((사람, NNG), 47)","((복지, NNP), 61)","((않, VX), 176)","((배우, VV), 98)","((문화, NNG), 32)","((중, NNB), 35)","((많, VA), 301)","((괜찮, VA), 43)","((동료, NNG), 59)","((주, VX), 171)"
14,"((않, VX), 43)","((배우, VV), 53)","((괜찮, VA), 171)","((않, VX), 95)","((사람, NNG), 30)","((주, VX), 34)","((커리, NNP), 293)","((않, VX), 37)","((자유, NNG), 59)","((최고, NNG), 158)"
15,"((성장, NNG), 41)","((식품, NNG), 50)","((복지, NNG), 163)","((보상, NNG), 94)","((많, VA), 28)","((괜찮, VA), 31)","((차이, NNG), 290)","((워라밸과, NA), 37)","((카카오, NNP), 57)","((돈, NNG), 151)"
16,"((업계, NNG), 40)","((괜찮, VA), 46)","((보, VV), 157)","((괜찮, VA), 92)","((주, VX), 27)","((급여, NNG), 29)","((급여, NNG), 280)","((사람, NNG), 36)","((복지, NNG), 55)","((미래, NNG), 145)"
17,"((괜찮, VA), 38)","((되, VV), 43)","((행복, NNG), 141)","((문화, NNG), 91)","((안정, NNG), 26)","((건설사, NNG), 29)","((기업, NNG), 250)","((많, VA), 35)","((팀, NNG), 55)","((괜찮, VA), 138)"
18,"((팀, NNG), 33)","((커리, NNP), 42)","((복지, NNP), 137)","((주, VX), 87)","((최고, NNG), 25)","((문화, NNG), 28)","((괜찮, VA), 248)","((급여, NNG), 32)","((않, VX), 51)","((생각, NNG), 138)"
19,"((엔터, NNG), 33)","((기업, NNG), 40)","((부서, NNP), 137)","((개발자, NNP), 86)","((욕심, NNP), 25)","((되, VV), 27)","((간, NNB), 241)","((건물, NNG), 31)","((대기업, NNP), 50)","((많, VA), 127)"

In [38]:
keywords_hannanum

,cjENM,cj제일제당,sk하이닉스,네이버,대한항공,삼성물산,삼성전자,아모레퍼시픽,카카오,현대자동차
0,"((회사, N), 646)","((회사, N), 864)","((회사, N), 2605)","((회사, N), 1700)","((회사, N), 567)","((회사, N), 550)","((회사, N), 5048)","((워라밸, N), 883)","((회사, N), 1102)","((회사, N), 3399)"
1,"((워라밸, N), 269)","((워라밸, N), 253)","((워라밸, N), 606)","((워라밸, N), 344)","((워라밸, N), 209)","((워라밸, N), 201)","((워라밸, N), 1199)","((회사, N), 794)","((워라밸, N), 788)","((워라밸, N), 2017)"
2,"((복지, N), 152)","((복지, N), 165)","((복지, N), 293)","((성장, N), 275)","((보장, N), 111)","((보장, N), 98)","((부, N), 568)","((보장, N), 306)","((보장, N), 283)","((보장, N), 720)"
3,"((보장, N), 127)","((대기업, N), 105)","((보장, N), 245)","((복지, N), 135)","((대기업, N), 34)","((삼성, N), 54)","((대기업, N), 466)","((복지, N), 132)","((성장, N), 110)","((대기업, N), 240)"
4,"((대기업, N), 49)","((보장, N), 100)","((부, N), 227)","((보장, N), 130)","((보수적, N), 32)","((대기업, N), 45)","((보장, N), 391)","((최고, N), 79)","((경영진, N), 106)","((직원, N), 221)"
5,"((사람, N), 43)","((성장, N), 76)","((직원, N), 215)","((팀, N), 119)","((직원, N), 31)","((복지, N), 41)","((복지, N), 368)","((팀, N), 55)","((복지, N), 90)","((연봉, N), 210)"
6,"((커리어, N), 40)","((부, N), 47)","((대기업, N), 189)","((최고, N), 114)","((사람, N), 27)","((미래, N), 39)","((최고, N), 358)","((성장, N), 40)","((문화, N), 90)","((급여, N), 178)"
7,"((성장, N), 36)","((문화, N), 45)","((급여, N), 176)","((보상, N), 93)","((욕심, N), 27)","((중, N), 35)","((돈, N), 336)","((문화, N), 36)","((최고, N), 87)","((최고, N), 155)"
8,"((업계, N), 36)","((연봉, N), 36)","((돈, N), 131)","((커리어, N), 90)","((최고, N), 25)","((급여, N), 26)","((차, N), 274)","((급여, N), 31)","((보상, N), 66)","((부, N), 152)"
9,"((문화, N), 33)","((사람, N), 35)","((행복, N), 130)","((개발자, N), 85)","((라벨, N), 23)","((성장, N), 26)","((급여, N), 274)","((미래, N), 31)","((카카오, N), 56)","((미래, N), 144)"
10,"((팀, N), 31)","((차, N), 32)","((구성원, N), 126)","((문화, N), 77)","((복지, N), 22)","((건설사, N), 26)","((기업, N), 204)","((건물, N), 30)","((팀, N), 54)","((차, N), 138)"
11,"((부, N), 29)","((급여, N), 32)","((차, N), 124)","((대기업, N), 74)","((안정적, N), 21)","((최고, N), 24)","((사람, N), 202)","((사람, N), 30)","((대기업, N), 49)","((생각, N), 137)"
12,"((차, N), 28)","((커리어, N), 31)","((개돼지, N), 124)","((동료들, N), 68)","((항공사, N), 21)","((가능, N), 20)","((만족, N), 176)","((차, N), 30)","((분위기, N), 43)","((문화, N), 132)"
13,"((콘텐츠, N), 27)","((생각, N), 30)","((경영진, N), 114)","((네이버, N), 67)","((급여, N), 21)","((연봉, N), 19)","((생각, N), 165)","((굿, N), 29)","((자유로운, N), 41)","((자동차, N), 109)"
14,"((엔터, N), 27)","((생산직, N), 26)","((최고, N), 98)","((만족, N), 64)","((생각, N), 21)","((건설회사, N), 18)","((커리어, N), 159)","((분위기, N), 25)","((사람, N), 40)","((중, N), 103)"
15,"((분위기, N), 26)","((기업, N), 25)","((삼성, N), 95)","((사람, N), 63)","((여행, N), 20)","((커리어, N), 18)","((네임밸류, N), 159)","((경영진, N), 24)","((차, N), 39)","((사람, N), 97)"
16,"((미래, N), 25)","((향상, N), 24)","((반도체, N), 91)","((기업, N), 63)","((경영진, N), 19)","((건설, N), 18)","((성장, N), 154)","((부, N), 24)","((연봉, N), 39)","((팀, N), 94)"
17,"((업무, N), 25)","((식품업계, N), 24)","((생각, N), 89)","((차, N), 62)","((문화, N), 18)","((듯, N), 17)","((문화, N), 154)","((만족, N), 24)","((커리어, N), 36)","((경영진, N), 93)"
18,"((경험, N), 22)","((겉, N), 23)","((사람, N), 86)","((부, N), 58)","((만족, N), 18)","((문화, N), 16)","((직원, N), 144)","((중, N), 22)","((동료들, N), 33)","((보상, N), 83)"
19,"((연봉, N), 21)","((중, N), 21)","((연봉, N), 85)","((경영진, N), 57)","((발전, N), 18)","((사람, N), 16)","((연봉, N), 140)","((업무, N), 21)","((부, N), 31)","((복지, N), 81)"

In [39]:
keywords_Okt

,cjENM,cj제일제당,sk하이닉스,네이버,대한항공,삼성물산,삼성전자,아모레퍼시픽,카카오,현대자동차
0,"((회사, Noun), 649)","((회사, Noun), 884)","((회사, Noun), 2620)","((회사, Noun), 1715)","((회사, Noun), 570)","((회사, Noun), 585)","((회사, Noun), 5099)","((밸, Noun), 904)","((회사, Noun), 1107)","((회사, Noun), 3414)"
1,"((워, Noun), 275)","((워, Noun), 256)","((워, Noun), 615)","((워, Noun), 356)","((워, Noun), 237)","((워, Noun), 204)","((워, Noun), 1238)","((워, Noun), 897)","((워, Noun), 813)","((워, Noun), 2079)"
2,"((밸, Noun), 273)","((밸, Noun), 253)","((밸, Noun), 612)","((밸, Noun), 351)","((밸, Noun), 213)","((밸, Noun), 201)","((밸, Noun), 1221)","((회사, Noun), 796)","((밸, Noun), 811)","((밸, Noun), 2069)"
3,"((복지, Noun), 152)","((복지, Noun), 176)","((복지, Noun), 299)","((복지, Noun), 136)","((보장, Noun), 119)","((보장, Noun), 99)","((돈, Noun), 691)","((보장, Noun), 312)","((보장, Noun), 286)","((보장, Noun), 734)"
4,"((보장, Noun), 128)","((대기업, Noun), 111)","((직원, Noun), 293)","((하는, Verb), 132)","((되는, Verb), 75)","((건설, Noun), 69)","((대기업, Noun), 474)","((되는, Verb), 173)","((되는, Verb), 186)","((되는, Verb), 517)"
5,"((되는, Verb), 79)","((보장, Noun), 101)","((돈, Noun), 286)","((보장, Noun), 131)","((다니기, Verb), 47)","((되는, Verb), 66)","((하는, Verb), 464)","((복지, Noun), 132)","((문화, Noun), 104)","((하는, Verb), 353)"
6,"((커리어, Noun), 60)","((하는, Verb), 95)","((하는, Verb), 276)","((커리어, Noun), 130)","((하는, Verb), 45)","((삼성, Noun), 62)","((부서, Noun), 440)","((다니기, Verb), 81)","((영진, Noun), 102)","((직원, Noun), 295)"
7,"((하는, Verb), 52)","((식품, Noun), 78)","((보장, Noun), 251)","((되는, Verb), 125)","((직원, Noun), 41)","((하는, Verb), 51)","((보장, Noun), 402)","((최고, Noun), 79)","((복지, Noun), 90)","((대기업, Noun), 250)"
8,"((대기업, Noun), 51)","((되는, Verb), 74)","((대기업, Noun), 197)","((최고, Noun), 115)","((돈, Noun), 37)","((대기업, Noun), 46)","((복지, Noun), 372)","((하는, Verb), 58)","((최고, Noun), 87)","((연봉, Noun), 214)"
9,"((사람, Noun), 47)","((문화, Noun), 62)","((되는, Verb), 188)","((동료, Noun), 108)","((대기업, Noun), 36)","((복지, Noun), 43)","((최고, Noun), 357)","((문화, Noun), 53)","((하는, Verb), 86)","((급여, Noun), 191)"
10,"((문화, Noun), 47)","((기업, Noun), 46)","((급여, Noun), 183)","((성장, Noun), 105)","((보수, Noun), 35)","((미래, Noun), 39)","((주는, Verb), 344)","((성장, Noun), 38)","((보상, Noun), 68)","((문화, Noun), 177)"
11,"((업계, Noun), 40)","((성장, Noun), 45)","((부서, Noun), 146)","((보상, Noun), 94)","((문화, Noun), 31)","((중, Noun), 35)","((되는, Verb), 314)","((팀, Noun), 36)","((동료, Noun), 59)","((안, Noun), 166)"
12,"((다니기, Verb), 39)","((업계, Noun), 42)","((구성원, Noun), 133)","((팀, Noun), 90)","((사람, Noun), 30)","((급여, Noun), 29)","((커리어, Noun), 292)","((사람, Noun), 36)","((카카오, Noun), 58)","((최고, Noun), 158)"
13,"((할, Verb), 33)","((커리어, Noun), 42)","((개돼지, Noun), 129)","((문화, Noun), 87)","((욕심, Noun), 28)","((문화, Noun), 28)","((차이, Noun), 287)","((기업, Noun), 33)","((성장, Noun), 51)","((돈, Noun), 151)"
14,"((성장, Noun), 30)","((생산, Noun), 39)","((차이, Noun), 128)","((할, Verb), 87)","((안정, Noun), 26)","((패션, Noun), 27)","((급여, Noun), 282)","((급여, Noun), 32)","((대기업, Noun), 50)","((미래, Noun), 151)"
15,"((콘텐츠, Noun), 28)","((직, Noun), 37)","((안, Noun), 115)","((개발자, Noun), 86)","((기업, Noun), 26)","((그냥, Noun), 27)","((기업, Noun), 262)","((미래, Noun), 32)","((커리어, Noun), 46)","((생각, Noun), 141)"
16,"((차이, Noun), 28)","((연봉, Noun), 37)","((삼성, Noun), 110)","((네이버, Noun), 84)","((항공, Noun), 25)","((않은, Verb), 27)","((간, Noun), 238)","((건물, Noun), 31)","((할, Verb), 45)","((자동차, Noun), 126)"
17,"((안, Noun), 27)","((사람, Noun), 37)","((행복, Noun), 107)","((사람, Noun), 78)","((최고, Noun), 25)","((다니기, Verb), 25)","((사람, Noun), 220)","((차이, Noun), 30)","((사람, Noun), 44)","((커리어, Noun), 124)"
18,"((엔터, Noun), 27)","((직원, Noun), 35)","((영진, Noun), 103)","((대기업, Noun), 77)","((라벨, Noun), 24)","((안, Noun), 25)","((직원, Noun), 220)","((굿, Noun), 29)","((팀, Noun), 43)","((기업, Noun), 123)"
19,"((업무, Noun), 27)","((부서, Noun), 35)","((간, Noun), 102)","((기업, Noun), 75)","((항공사, Noun), 24)","((최고, Noun), 25)","((잘, Verb), 213)","((커리어, Noun), 29)","((분위기, Noun), 43)","((차이, Noun), 113)"

In [29]:
vectorize(df, '네이버')

                                           리뷰       Above_T top_keyword
0                      생각보다 여러모로 퇴보적이고 경직된 회사  [생각보다, 여러모로]        여러모로
1                                 시쳇말로 육각형 회사         [육각형]         육각형
2                                       좋은 회사          [좋은]          좋은
3                    워라밸 보장되고 복지 급여 상위 티어급 회사            []        보장되고
4                              워라밸 부서 간 차이 있음            []          부서
...                                       ...           ...         ...
3173                                 네임밸류 최강임        [네임밸류]        네임밸류
3174  전반적으로 만족스러운 직장  성장의 정점에 다다랐나 싶어서 다소 불안함            []          다소
3175            성장하려는 의지만 있다면 무한히 성장할 수 있는 회사         [의지만]         의지만
3176      수평적인 분위기로 자유로워 보이지만 평가를 받아야 한다는 압박감         [평가를]         평가를
3177          개발자로서 좋은 대우를 받으며 꾸준히 성장할 수 있는 곳         [대우를]         대우를

[3178 rows x 3 columns]

In [33]:
# 키워드 조합을 확인하기

name = input("['cjENM', 'cj제일제당', 'sk하이닉스', '네이버', '대한항공', '삼성물산', '삼성전자', '아모레퍼시픽', '카카오', '현대자동차']: ")

print('기업 이름: ', name, '\n')
print('\n')
collocation(df, name)

['cjENM', 'cj제일제당', 'sk하이닉스', '네이버', '대한항공', '삼성물산', '삼성전자', '아모레퍼시픽', '카카오', '현대자동차']: 네이버
기업 이름:  네이버

     Bi_gram       Tri_gram          Quad_gram
0   (금융, 치료)    (대, 환장, 파티)     (풀, ㄹ, 재택, 유지)
1    (뽕, 취하)   (만의, 잔치, 관성)  (조직별, 상황, 마다, 다르)
2   (정신, 차리)   (직장, 내, 괴롭히)  (서마다, 상황, 마다, 다르)
3    (투, 더ㄹ)  (조직별, 상황, 마다)      (워워, 배, ㄹ, 리)
4   (환장, 파티)      (꾸, ㄹ, 빨)   (부, 서마다, 상황, 마다)
5   (넘, 었는데)    (대우, 받, 으며)     (리, 더어, 잘, 만나)
6  (대감집, 노비)  (생각, 보다, 체계적)    (직장, 내, 괴롭히, ㅁ)
7     (워, 베)      (워, 베, ㄹ)    (상황, 마다, 다르, ㅁ)
8   (개발직, 군)   (상황, 마다, 다르)      (번, 쯤, 경험, 보)
9   (꼼수, 꼼수)  (서마다, 상황, 마다)   (처우, 만족, 스럽, 으나)